#!/usr/bin/env python3
"""
Inject the GA4 tag into every page's <head>.

This site keeps <head> per-page (only the header and footer are partials), so the
tag has to be written into all 26 files. Same contract as tools/add-schema.py:
the block is wrapped in BEGIN/END markers, regenerated on every build, and must
never be hand-edited in the output — edit this file instead.

  python3 tools/add-analytics.py            # write
  python3 tools/add-analytics.py --check    # exit 1 if any page is stale

BOT GATING
----------
The sister site junegiriyatra.com gates its GA4 tag to real human browsers
(src/components/Analytics.tsx) because GA4's built-in "known bots" filter does
not catch headless Chrome from a datacentre. Its numbers are de-botted at source
as a result. This mirrors that logic in vanilla JS so the two properties count
the same thing and can be compared honestly.

Set GATE_BOTS = False to emit Google's stock snippet instead.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MARKER = "analytics"
MEASUREMENT_ID = "G-MNEGYBP53S"      # JuneGiri Farms — GA4 web stream
GATE_BOTS = True

# Kept deliberately in sync with BOT_UA in ~/junegiriyatra/src/components/Analytics.tsx.
BOT_UA = (r"bot|crawl|spider|slurp|headless|phantom|puppeteer|playwright|selenium|lighthouse|"
          r"chrome-lighthouse|pagespeed|gtmetrix|pingdom|uptime|statuscake|datadog|newrelic|"
          r"prerender|scrapy|python-requests|python-urllib|aiohttp|httpx|axios|node-fetch|"
          r"go-http-client|okhttp|java\/|curl\/|wget|libwww|apache-httpclient|facebookexternalhit|"
          r"whatsapp|telegrambot|bingpreview|gptbot|chatgpt-user|ccbot|claudebot|anthropic-ai|"
          r"perplexitybot|google-extended|applebot|yandexbot|ahrefsbot|semrushbot|mj12bot|"
          r"dotbot|petalbot|bytespider")

STOCK = f"""<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id={MEASUREMENT_ID}"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){{dataLayer.push(arguments);}}
gtag('js', new Date());
gtag('config', '{MEASUREMENT_ID}');
</script>"""

# Loads gtag.js only for real browsers. dataLayer is primed first, which is safe:
# gtag() queues into dataLayer and the library drains it once it arrives.
GATED = f"""<!-- Google tag (gtag.js) — loaded for human browsers only -->
<script>
(function () {{
  var BOT = /{BOT_UA}/i;
  var ua = navigator.userAgent || '';
  if (navigator.webdriver || !ua || BOT.test(ua) ||
      window.__nightmare || window._phantom || window.callPhantom) return;
  window.dataLayer = window.dataLayer || [];
  function gtag() {{ dataLayer.push(arguments); }}
  window.gtag = gtag;
  gtag('js', new Date());
  gtag('config', '{MEASUREMENT_ID}');
  var s = document.createElement('script');
  s.async = true;
  s.src = 'https://www.googletagmanager.com/gtag/js?id={MEASUREMENT_ID}';
  document.head.appendChild(s);
}})();
</script>"""


def block():
    return (f"<!-- BEGIN {MARKER} — generated by build.sh, edit tools/add-analytics.py -->\n"
            f"{GATED if GATE_BOTS else STOCK}\n"
            f"<!-- END {MARKER} -->")


EXISTING = re.compile(rf"<!-- BEGIN {MARKER}.*?<!-- END {MARKER} -->\n?", re.DOTALL)


def main():
    check = "--check" in sys.argv
    changed = []

    for path in sorted(ROOT.glob("*.html")):
        html = path.read_text()
        stripped = EXISTING.sub("", html)

        if "<head>" not in stripped:
            print(f"  !! {path.name}: no <head>, skipped")
            continue

        # As early in <head> as possible — but AFTER <meta charset>. The block is ~1.5 KB,
        # so putting it first would shove the charset declaration past the 1024 bytes
        # browsers sniff for encoding, and these pages carry ₹ and ·.
        charset = re.search(r"<meta[^>]+charset[^>]*>", stripped, re.I)
        if charset:
            at = charset.end()
            new = stripped[:at] + "\n" + block() + stripped[at:]
        else:
            new = stripped.replace("<head>", "<head>\n" + block(), 1)

        if new != html:
            changed.append(path.name)
            if not check:
                path.write_text(new)

    label = "stale" if check else "updated"
    print(f"analytics: {len(list(ROOT.glob('*.html')))} pages, {len(changed)} {label}"
          f"{' (' + MEASUREMENT_ID + (', bot-gated' if GATE_BOTS else '') + ')' if changed or not check else ''}")

    if check and changed:
        print("  stale: " + ", ".join(changed))
        print("  run ./build.sh")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
