#!/usr/bin/env python3
"""Regenerate _redirects so every URL variant reaches the canonical URL in one 301.

Two problems this fixes:

1. The hand-written trailing-slash rules pointed at `.html`, and Cloudflare Pages
   then rewrote `.html` to the extensionless URL with a **307**. So `/stay/` took
   two hops with mixed permanence: 301 -> /stay.html -> 307 -> /stay. Chains
   dilute link equity and waste crawl budget.

2. A 307 is a *temporary* redirect. It tells Google the move may be reversed, so
   the source URL is kept in the index and signal consolidation never settles.
   Every `.html` URL therefore needs an explicit 301 override.

The canonical form is extensionless and slash-free: https://junegirifarms.com/stay

Run via ./build.sh. Generated from the pages that actually exist, so adding a
page cannot leave a stale or missing rule behind.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Excluded from the deploy via .assetsignore.
SKIP = {"brochure-print.html"}

# Old URL -> current URL, for pages that have moved. Keep these forever: the old
# URL may still be printed on something, or sitting in someone's chat history.
LEGACY = {
    # The café menu had its own page for a few hours on 2026-09-28. It is now a
    # photo of the printed card inside the meals section of /stay.
    "/menu": "/stay",
    "/cafe": "/stay",
    # Yoga moved to the dedicated site junegiriyogretreats.com (Oct 2026).
    # The Reset Retreat and 200-hr TTC pages now live there.
    "/retreat": "https://junegiriyogretreats.com/",
    "/retreat.html": "https://junegiriyogretreats.com/",
    "/ttc": "https://junegiriyogretreats.com/",
    "/ttc.html": "https://junegiriyogretreats.com/",
}

HEADER = """# GENERATED by tools/gen-redirects.py — edit that script, not this file.
#
# Canonical URL form is extensionless with no trailing slash: /stay
# Every other variant 301s straight to it, in a single hop.
#   /stay/       -> /stay   (301, was: 301 to /stay.html then a 307)
#   /stay.html   -> /stay   (301, overrides the Cloudflare Pages default 307)
#
# No rule for the bare "/" — a root trailing-slash rule would loop.
#
# LEGACY holds URLs that no longer exist as pages. They cannot be derived from
# the directory, so they are listed by hand and emitted last.
"""


def main():
    pages = sorted(p.stem for p in ROOT.glob("*.html") if p.name not in SKIP)
    width = max(len(s) for s in pages) + len("/.html") + 2

    lines = [HEADER]
    lines.append("# --- .html -> canonical -------------------------------------------------")
    lines.append(f"{'/index.html'.ljust(width)}/                301")
    for stem in pages:
        if stem == "index":
            continue
        lines.append(f"{f'/{stem}.html'.ljust(width)}/{stem.ljust(width - 2)}301")

    lines.append("")
    lines.append("# --- trailing slash -> canonical ----------------------------------------")
    for stem in pages:
        if stem == "index":
            continue
        lines.append(f"{f'/{stem}/'.ljust(width)}/{stem.ljust(width - 2)}301")
    lines.append("")

    if LEGACY:
        lines.append("# --- moved pages --------------------------------------------------------")
        for src, dest in sorted(LEGACY.items()):
            # Both variants, the same way a live page gets both.
            for variant in (src, src + "/"):
                lines.append(f"{variant.ljust(width)}{dest.ljust(width - 1)}301")
        lines.append("")

    (ROOT / "_redirects").write_text("\n".join(lines), encoding="utf-8")
    total = (len(pages) - 1) * 2 + 1 + len(LEGACY) * 2
    print(f"_redirects: {total} rules for {len(pages)} pages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
