#!/usr/bin/env python3
"""Bake partials/header.html + partials/footer.html into every page.

Two jobs:

1. Replace the client-side slots (<div data-include="header"></div>) with the
   real markup, wrapped in BEGIN/END markers so re-running is idempotent.
   Without this the served HTML contains no internal links at all -- the nav
   only existed after JS ran.

2. Rewrite internal ".html" hrefs to the clean extensionless URLs the
   canonicals and sitemap already use (stay.html -> /stay). Serving
   /stay.html 307s to /stay, so every internal link was costing a redirect hop.

Idempotent: safe to run repeatedly. Run via ./build.sh.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Pages that are deliberately standalone (excluded from the deploy via
# .assetsignore) and must not get the site chrome.
SKIP = {"brochure-print.html"}


def clean_url(filename: str) -> str:
    """stay.html -> /stay ; index.html -> /"""
    stem = filename[: -len(".html")]
    return "/" if stem == "index" else "/" + stem


def rewrite_links(html: str, page_names: set) -> str:
    """href="stay.html" -> href="/stay" for real pages only."""

    def sub(match):
        quote, target = match.group(1), match.group(2)
        if target not in page_names:
            return match.group(0)
        return f'href={quote}{clean_url(target)}{quote}'

    return re.sub(r'href=(["\'])([A-Za-z0-9._-]+\.html)\1', sub, html)


def inline(html: str, partials: dict) -> str:
    """Replace each data-include slot with its partial, between markers."""
    for name, markup in partials.items():
        block = (
            f"<!-- BEGIN partial:{name} — generated by build.sh, "
            f"edit partials/{name}.html -->\n"
            f"{markup.strip()}\n"
            f"<!-- END partial:{name} -->"
        )
        # Fresh slot, or a previously generated block (so re-runs update it).
        slot = re.compile(
            rf'<div\s+data-include=["\']{name}["\']\s*>\s*</div>'
            rf'|<!-- BEGIN partial:{name}.*?<!-- END partial:{name} -->',
            re.DOTALL,
        )
        html = slot.sub(lambda _: block, html)
    return html


def main(argv):
    check_only = "--check" in argv

    pages = sorted(p for p in ROOT.glob("*.html") if p.name not in SKIP)
    page_names = {p.name for p in pages} | SKIP

    partials = {
        p.stem: p.read_text(encoding="utf-8")
        for p in sorted((ROOT / "partials").glob("*.html"))
    }
    # Partials link to pages too -- clean those before they get inlined.
    partials = {k: rewrite_links(v, page_names) for k, v in partials.items()}

    changed = []
    for page in pages:
        original = page.read_text(encoding="utf-8")
        updated = rewrite_links(inline(original, partials), page_names)
        if updated != original:
            changed.append(page.name)
            if not check_only:
                page.write_text(updated, encoding="utf-8")

    if check_only:
        if changed:
            print(f"out of date: {', '.join(changed)}")
            return 1
        print("up to date")
        return 0

    print(f"inlined {', '.join(partials)} into {len(pages)} pages")
    print(f"updated {len(changed)} file(s)" if changed else "no changes")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
